### ISSUE TITLE
Question: line-oriented vs byte

### ISSUE THREAD

**Issue by greencardamom** [circulosmeos/gztool#1]
Hi,

I work with large text files using commands like 'tail -n +40000 file.txt | head -n 1000' which retrieves lines 40000-41000. This feeds chunks of data to a program. The program needs to know which line numbers are being processed; and it operates on multiple files at once, getting the same line number blocks from each even though they have different data.

Is it possible to retrieve in line-oriented mode instead of byte? I imagine if the index proxied bytes for line numbers, for example determine the byte number at each 1,000 line block of text when creating the index so it knows that line 41000 is at byte #xyz. When creating the index specify a line-oriented block size eg. 1,000

This probably seems like a special application but I think many/most people work with text files in line-oriented mode vs. byte count otherwise lines are truncated and data lost and not able to control which lines are retrieved. Thanks for you consideration and work on this project!

**Comment by circulosmeos** [comment]
Hi @greencardamom 
That's an interesting proposal! Thanks for the feedback.
**It seems feasible**... I'll carefully think about this to see if it can be implemented in a compatible way with all the other code.
I do also work with text files: but mostly log files so I do not need exact line numbering. You probably work with chromosome sequencing? :-)

**Comment by greencardamom** [comment]
Hi, I'm working with Wikipedia, building tools for various projects. It's in shared server environment, memory and cpu are key to keep low. I developed a light system for storing API results and caching for later use, low memory and cpu. If it can store and retrieve the data in compressed format it will keep disk usage low, also. 
Another option is if there is a way to determine what byte # line 1000 starts and emit that information during compression my program can pick it up from there, it can inform gztool where to start uncompressing (though I am unclear how to uncompress a block of text between two byte #s).

**Comment by circulosmeos** [comment]
wow, cool project!
With the modification I have in mind, you would just have to generate the index with an eXtended parameter to count/store lines: `gztool -x` and decompress indicating the line number from which to start: `gztool -L 70k` (for example). The index generated with `-x` would not be compatible with previous versions of gztool (but will be as small), but this isn't important now because I'm probably the only frequent user of `gztool` :-)

PS: you would be trading space for cpu, but also disk access times would be lowered because of the (almost) direct access to the lines as opposite to reading the entire file until a line as done with `tail`, so it probably will worth it!

**Comment by circulosmeos** [comment]
Almost there!
New version will have `-x` parameter to generate indexes on files with *nix/windows new lines (this includes Mac OS X and above), and `-X` to use ' \r' as newline (old Mac format).

**Comment by circulosmeos** [comment]
**v0.10 with line number support is ready!**
To generate an index with line numbers information, use `gztool -x`.
To retrieve data from a line number use `gztool -L #`.
`-L` accepts suffixes [kmgtpe] like `-b`.

PS: As always, `-L` can be used even if the index does not exist, and `gztool` will both extract data and create the index for future fast use at the same time.

**Comment by greencardamom** [comment]
That is awesome circulosmeos. I will give it a try and see how it goes!
