### ISSUE TITLE
Impossible to download gztool-Windows.x86_64.exe in version 1.7.0

### ISSUE THREAD

**Issue by elechopier** [circulosmeos/gztool#21]
Hi,

We try for several days to download the latest 1.7.0 windows executable and it fails.
Here is wget command:
wget.exe https://github.com/circulosmeos/gztool/releases/download/v1.7.0/gztool-Windows.x86_64.exe
--2024-11-26 10:25:03--  https://github.com/circulosmeos/gztool/releases/download/v1.7.0/gztool-Windows.x86_64.exe
Resolving github.com... 140.82.121.4
Connecting to github.com|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/197959335/9bf65825-15d1-4067-8157-3ab08938ced4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241126%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241126T092345Z&X-Amz-Expires=300&X-Amz-Signature=bba0aed4121539cd9ecd8fa54b67d03796f962790e14d7457add6a2fa3d9d87e&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgztool-Windows.x86_64.exe&response-content-type=application%2Foctet-stream [following]
--2024-11-26 10:25:03--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/197959335/9bf65825-15d1-4067-8157-3ab08938ced4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241126%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241126T092345Z&X-Amz-Expires=300&X-Amz-Signature=bba0aed4121539cd9ecd8fa54b67d03796f962790e14d7457add6a2fa3d9d87e&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgztool-Windows.x86_64.exe&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to objects.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 277807 (271K) [application/octet-stream]
Saving to: 'gztool-Windows.x86_64.exe'

gztool-Windows.x86_64.exe     100%[=================================================>] 271,30K  --.-KB/s    in 0,06s

utime(gztool-Windows.x86_64.exe): No such file or directory
2024-11-26 10:25:39 (4,63 MB/s) - 'gztool-Windows.x86_64.exe' saved [277807/277807]

With previous version 1.6.1, there is no problem.

Regards,

**Comment by circulosmeos** [comment]
Hi @elechopier 
The file seems accesible for me, even from different world locations (I've tried Europe and USA).
Your output is quite strange as the file seems downloaded: 277807 bytes is the correct size and wget prints it as "saved".
The file should be in your filesystem... the only strange line is that
`utime(gztool-Windows.x86_64.exe): No such file or directory`
which doesn't seem wget-related ???
Can you check it now?
