### ISSUE TITLE
Feature request: Random access when using stdin

### ISSUE THREAD

**Issue by fiddyschmitt** [circulosmeos/gztool#4]
Hi Roberto,

Could you please implement a new argument, which informs gztool which compressed byte it's about to receive in stdin?

Something like:
`gztool.exe -ecb 1501239288 -b 3410890441`

Where `-ecb` stands for 'Expect compressed byte'

**Background**
The -b argument is great for telling telling gztool which uncompressed byte to start extracting from. That works really well if working with concrete files.

However I'm writing a program which doesn't use concrete files, rather uses in-memory content. In order to use the -b argument, I've used the technique you described [here](https://unix.stackexchange.com/questions/429197/reading-partially-downloaded-gzip-with-an-offset/#541903), which makes use of sparse files.

For example, if I would like to get uncompressed bytes 3,410,890,441 - 4,000,000,000, I first run `gztool.exe -ll` to work out which part of the compressed file contains that portion. In this case 1,501,239,288 - 1,630,240,888. I then create a sparse file and populate that section with the compressed data. (The sparse file in this example only takes up 123MB). Then finally I run gztool on the sparse file:
`gztool -W -I "file.gzi" -b 3410890441 <sparseGzipFilename>` and read from stdout.

That technique works perfectly. The only issue is that there is unnecessary IO (I have to populate a sparse file every time I want to decompress something). So using the `-ecb` argument would mean I could just send compressed data straight into gztool's stdin, and it would output decompressed data.

Cheers,
Fidel

**Comment by circulosmeos** [comment]
Hi Fidel,
Your suggestion makes perfect sense!
Just let me time to think about it and how it can be implemented... for now it seems feasible.

NB: I'd use a single letter as parameter (I use C's getopt())... probably '-n', for 'next compressed byte', as most other letters like 'e', 'b' or 'x' are already used... I'll end up exhausting the alphabet.

**Comment by circulosmeos** [comment]
As for the unnecessary I/O, I've been thinking about it, and it should not pose any speed decrement afaik: nor the writing by the OS (sparse files are just filled with a number counting the zeros filled there) neither the reading by gztool (because it fseek() to `-b`, which if correctly implemented by the OS, should just immediately jump to the data) should consume additional time.

That said, the new parameter would be cool, as it would remove the need for a sparse file creation... which is always filesystem dependant and mostly kind of a hack :-)

**Comment by fiddyschmitt** [comment]
Haha yes, and a beautiful hack it is 😁

Thank you for considering the request.

You're right about the I/O. The sparse file is created and populated very quickly, and gztool can seek through it very efficiently. I meant that it was unnecessary I/O only in the sense that I had to write the data from RAM into the sparse file, rather than passing the data straight into gztool.

**Comment by circulosmeos** [comment]
Hi @fiddyschmitt 
Finally it was easier than expected: I've just released v0.11 with `-n` parameter to indicate **next expected byte in input**.
So for example if 10 bytes have been cut off, then -n must be 11: `-n 11`.
This way `-n 1` is a synonym for just no `-n`, that is, a complete gzip file.
Let me know if this runs ok.

**Comment by fiddyschmitt** [comment]
Fantastic! Thanks so much. I'll integrate it this weekend and let you know how it goes.

**Comment by fiddyschmitt** [comment]
Glorious! It works perfectly! Many thanks @circulosmeos

**Comment by circulosmeos** [comment]
Perfect!
