### ISSUE TITLE
Feature request: Multiple input files

### ISSUE THREAD

**Issue by fiddyschmitt** [circulosmeos/gztool#7]
Hi Roberto,

Clonezilla splits gzip files into 4GB segments. Would it be possible to enable gztool to accept multiple input files and treat them as one big input file?

eg.
`gztool -I myindex.gzi "sda4.ntfs-ptcl-img.gz.aa" "sda4.ntfs-ptcl-img.gz.ab" "sda4.ntfs-ptcl-img.gz.ac"`

I want to avoid using cat to combine the files
eg.
`cat *sda4* | gztool -I myindex.gzi`
because I create the index over multiple gztool runs; so I want to avoid providing data which has already been indexed by gztool.

Thank you,
Fidel

**Comment by circulosmeos** [comment]
Hi @fiddyschmitt 
I must think a little bit about this: 
I'll let you know what I decide :-)

**Comment by fiddyschmitt** [comment]
Hi Roberto,
I no longer need this, as I create a stream which stiches all the individual files together.

Thanks!
Fidel

**Comment by circulosmeos** [comment]
Good to hear that!
I didn't find a "fine" way to implement a multiple file input with all the options that `gztool` has 🤷‍♂️

**Comment by circulosmeos** [comment]
Good to hear that!
I didn't find a "fine" way to implement a multiple file input with all the options that `gztool` has 🤷‍♂️
