### ISSUE TITLE
Functional question.

### ISSUE THREAD

**Issue by semmjon** [circulosmeos/gztool#8]
I would like to be able to unzip truncated data with a range request without using transfer encoding. 
How do I raise the first index point so that I can make larger cuts?

Thanks : )

**Comment by circulosmeos** [comment]
Hi @semmjon 

I do not understand this:

> ... without using transfer encoding

The first index point is always coded at uncompressed byte 0, and after that no matter how many/few index points are stored, you can choose any of them to make the cut (read about the **previous byte necessity** in the examples).
Anyway, the space between index points can be raised from 10 MiB between uncompressed bytes to any value you want, for example 100 MiB, with `-n` parameter: `-n 100`.

Have I understood correctly your question?

What are you using ´gztool´ for? Just for curiosity :-)

**Comment by semmjon** [comment]
Hi :)
With an API request (in this case from an S3 bucket) you can theoretically unzip files on the server side and even select columns / rows with a "SelectObjectContent" (S3) request. 
For this purpose, "Transferencoding: chunked, gzip" is given in the request header. 
You can also specify which byte range you want to get (with "Range: bytes = m -... n).

However, I believe that unzipping is still takes more time compared to the index file. 
That's why I wanted to make a request in which I only get part of the Gzip file (e.g. half of it) and then start unpacking it from halfway through.

Currently I am unable to set the first index point higher or rather get an error if the -n parameter is too high. 
Can I set this indexpoint when indexing with -s, or how does it work?

Thank you: D

**Comment by circulosmeos** [comment]
**The index must be constructed previously, with access to the complete gzip file.**
The advantage of using gztool comes in next extractions, when the index already exists and the source gzip file can be read in the middle, or cut.

I don't know if next paragraphs clarifiy `gztool` operation, or if it can fit your needs: you *need* the index (a previous run of `gztool` over the gzip data) previously to being able to use just chunks of the original gzip file. Also, *is `gztool` who selects and inserts the index entry points in the index file*, spaced approx. N uncompressed-MiBytes, based on `-s N` parameter (10 uncompressed-MiB by default).
You can also [read this introduction to gztool operation with drawings](http://circulosmeos.wordpress.com/2019/08/11/continuous-tailing-of-a-gzip-file-efficiently/).

Once the index has been constructed, it doesn't matter where you want to extract things, as far as there's an index point in the index previous to the start of the first byte that you want to extract.
That's the reason why I say that the first index point has no special meaning: the index file will contain dozens or hundreds of index points, and gztool will select the most appropiate based on `-b` (byte) or `-L` (line, if index is created with `-x`) values.
`-s` parameter controls the (**uncompressed**) distance between those points: the higher the distance, the bigger the chunks from the original gzip may be needed, and more data may be pre-unzipped until reaching the desired byte point - the lower the distance, the quickest and smaller will be the previous data needed until find the desired byte point, but the bigger the index will be.

With a default value of `-s 10`, the index file occupy about 0.3% of the size of the gzip file.
So, with `-s 1`, the index file will occupy a 3%, and with `-s 100` a 0.03%, with `-s 1000` (1 MB) a 0.003%, etc...
If a `-s 1000` would be use, and for example you want to extract a byte from 1500 MB on, you would need a chunk of the gzip file from 1000 MB on (the index point will be somewhere there: `-l` show the exact locations), thus requiring a lot of unnecessary data (probably not 500 MB more, as this is the uncompressed value... but if compression is ~50%, then 250 MB more are needed...).
If a `-s 10` is used, on average only 5 MB more data before the desired byte is needed (or about 2.5 MB at 50% gzip compression ratio).

**Comment by semmjon** [comment]
Hi, Thanks in advance for the detailed explanation :-)
Of course I would only ask questions after I have read the documentation, which I have, 
but it was unclear to me whether it is possible to cut and unzip a cut file beyond 10000 bytes.

I also understood that an index file is required before i can access a random position. 
With a -b command, I need the entire file up to the relevant byte locally (at least that's how I understood it).
So if I only have a sliced file, I can't read from the middle unless I have an indexpoint and execute it with -n.

**Comment by circulosmeos** [comment]
> but it was unclear to me whether it is possible to cut and unzip a cut file beyond 10000 bytes.

Yes. There's no limit.

> With a -b command, I need the entire file up to the relevant byte locally

No. If index file is available, you just need the truncated gzip file from the last index point entry before the `-b` value. See example here: https://unix.stackexchange.com/questions/429197/reading-partially-downloaded-gzip-with-an-offset/#541903

> Here I get the error "is beyond required index point"

Pass me an `ls -l` of your gzip, truncated gzip and .gzi files, the output of `gztool -ll your-index-file.gzi` and the complete command you're trying with `-n` so I can advise you.

**Comment by semmjon** [comment]
Hi, thanks again for this feedback, unfortunately I only came to test it again now. 
What I set wrong was the -b parameter. 
I had assumed that a cut file would start again from 0 bytes.
Thanks for the tool. It's really handy for ETL, especially if you want to access a file frequently. :+1:

Best, Semjon

**Comment by circulosmeos** [comment]
Thanks to you for leaving us a case of use ! 👍
